services:
  redis:
    image: redis:7-alpine
    container_name: redis-sensore
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: api-sensore
    depends_on:
      - redis
    restart: unless-stopped

  sensore:
    build:
      context: ./sensor
    container_name: sensore-compose
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - C:\log-sensore:/app/log

  frontend:
    build:
      context: ./frontend
    container_name: frontend-sensore
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  redis_data: